# Generated by Django 5.2 on 2025-05-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('emergency', 'Emergency'), ('special', 'Special Drive')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='camp',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='campregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campregistration',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
